sudo: required
services:
  - docker

before_install:
  - docker build -t jelenaJelenko/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jelenaJelenko/react-test npm run test -- --coverage

after_success:
  - docker build -t jelenaJelenko/multi-client ./client
  - docker build -t jelenaJelenko/multi-nginx ./nginx
  - docker build -t jelenaJelenko/multi-server ./server
  - docker build -t jelenaJelenko/multi-worker ./worker
  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images
  - docker push jelenaJelenko/multi-nginx
  - docker push jelenaJelenko/multi-client
  - docker push jelenaJelenko/multi-server
  - docker push jelenaJelenko/multi-worker